# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-ast
  - id: check-toml
- repo: https://github.com/psf/black
  rev: 21.11b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: "4.0.1"
  hooks:
  - id: flake8
    args: [--max-line-length=88]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
- repo: local
  hooks:
  - id: version
    name: Ensure same package version in all modules
    entry: ./.check_version
    language: system
    always_run: true
